export const chartOfAccounts = [
  { code: '1', name: 'FFLDS', description: 'Bank', type: 'Bank', taxRate: 'BAS Excluded' },
  { code: '200', name: 'Sales', description: 'Income from any normal business activity', type: 'Revenue', taxRate: 'GST Free Income' },
  { code: '230', name: 'Rent Revenue', description: 'Rent paid to FFLDS, rental agreement in place', type: 'Revenue', taxRate: 'GST Free Income' },
  { code: '260', name: 'Other Revenue', description: 'Any other income that does not relate to normal business activities and is not recurring', type: 'Revenue', taxRate: 'GST on Income' },
  { code: '270', name: 'Interest Income', description: 'Interest income', type: 'Revenue', taxRate: 'GST Free Income' },
  { code: '310', name: 'Cost of Goods Sold', description: 'Cost of goods sold by the business', type: 'Direct Costs', taxRate: 'GST on Expenses' },
  { code: '400', name: 'Advertising', description: 'Expenses incurred for advertising while trying to increase sales', type: 'Expense', taxRate: 'GST on Expenses' },
  { code: '404', name: 'Bank Fees', description: 'Fees charged by your bank for transactions regarding your bank account(s).', type: 'Expense', taxRate: 'GST Free Expenses' },
  { code: '405', name: 'Filing Fees', description: 'ASIC Fee', type: 'Expense', taxRate: 'BAS Excluded' },
  { code: '408', name: 'Cleaning', description: 'Expenses incurred for cleaning business property.', type: 'Expense', taxRate: 'GST on Expenses' },
  { code: '409', name: 'Client Amenities', description: 'Client boarding purchases, food, etc', type: 'Expense', taxRate: 'GST on Expenses' },
  { code: '412', name: 'Consulting & Accounting', description: 'Expenses related to paying consultants', type: 'Expense', taxRate: 'GST on Expenses' },
  { code: '413', name: 'WHS Expense', description: 'Work health and safety related items such as security patrols.', type: 'Expense', taxRate: 'GST on Expenses' },
  { code: '416', name: 'Depreciation', description: "The amount of the asset's cost (based on the useful life) that was consumed during the period", type: 'Expense', taxRate: 'BAS Excluded' },
  { code: '420', name: 'Entertainment', description: 'Expenses paid by company for the business but are not deductable for income tax purposes.', type: 'Expense', taxRate: 'GST on Expenses' },
  { code: '425', name: 'Freight & Courier', description: 'Expenses incurred on courier & freight costs', type: 'Expense', taxRate: 'GST on Expenses' },
  { code: '429', name: 'General Expenses', description: 'General expenses related to the running of the business.', type: 'Expense', taxRate: 'GST on Expenses' },
  { code: '433', name: 'Insurance', description: "Expenses incurred for insuring the business' assets", type: 'Expense', taxRate: 'GST on Expenses' },
  { code: '437', name: 'Interest Expense', description: 'Any interest expenses paid to ATO, business bank accounts or credit card accounts.', type: 'Expense', taxRate: 'GST Free Expenses' },
  { code: '441', name: 'Legal expenses', description: 'Expenses incurred on any legal matters', type: 'Expense', taxRate: 'GST on Expenses' },
  { code: '445', name: 'Light, Power, Heating', description: 'Expenses incurred for lighting, powering or heating the premises', type: 'Expense', taxRate: 'GST on Expenses' },
  { code: '446', name: 'Water Rates', description: 'Water bills', type: 'Expense', taxRate: 'GST Free Expenses' },
  { code: '449', name: 'Motor Vehicle Expenses', description: 'Expenses incurred on the running of company motor vehicles', type: 'Expense', taxRate: 'GST on Expenses' },
  { code: '452', name: 'Disability House Expenses', description: 'General expenses related to the running of the house', type: 'Expense', taxRate: 'GST on Expenses' },
  { code: '453', name: 'Office Expenses', description: 'General expenses related to the running of the business office.', type: 'Expense', taxRate: 'GST on Expenses' },
  { code: '454', name: 'Medical equipment rental', description: 'Rented medical devices or medical equipment', type: 'Expense', taxRate: 'GST on Expenses' },
  { code: '461', name: 'Printing & Stationery', description: 'Expenses incurred by the entity as a result of printing and stationery', type: 'Expense', taxRate: 'GST on Expenses' },
  { code: '469', name: 'Rent', description: 'The payment to lease a building or area.', type: 'Expense', taxRate: 'GST Free Expenses' },
  { code: '473', name: 'Repairs and Maintenance', description: 'Expenses incurred on a damaged or run down asset that will bring the asset back to its original condition.', type: 'Expense', taxRate: 'GST on Expenses' },
  { code: '477', name: 'Wages and Salaries', description: 'Payment to employees in exchange for their resources', type: 'Expense', taxRate: 'BAS Excluded' },
  { code: '478', name: 'Superannuation', description: 'Superannuation contributions', type: 'Expense', taxRate: 'BAS Excluded' },
  { code: '479', name: 'Staff Amenities', description: 'Providing refreshments and minor comforts to employees during their working hours.', type: 'Expense', taxRate: 'GST on Expenses' },
  { code: '485', name: 'Subscriptions', description: 'E.g. Magazines, professional bodies.', type: 'Expense', taxRate: 'GST on Expenses' },
  { code: '489', name: 'Telephone & Internet', description: 'Expenditure incurred from any business-related phone calls, phone lines, or internet connections', type: 'Expense', taxRate: 'GST on Expenses' },
  { code: '493', name: 'Travel - National', description: 'Expenses incurred from domestic travel which has a business purpose', type: 'Expense', taxRate: 'GST on Expenses' },
  { code: '494', name: 'Travel - International', description: 'Expenses incurred from international travel which has a business purpose', type: 'Expense', taxRate: 'GST Free Expenses' },
  { code: '497', name: 'Bank Revaluations', description: 'Bank account revaluations due for foreign exchange rate changes', type: 'Expense', taxRate: 'BAS Excluded' },
  { code: '498', name: 'Unrealised Currency Gains', description: 'Unrealised currency gains on outstanding items', type: 'Expense', taxRate: 'BAS Excluded' },
  { code: '499', name: 'Realised Currency Gains', description: 'Gains or losses made due to currency exchange rate changes', type: 'Expense', taxRate: 'BAS Excluded' },
  { code: '505', name: 'Income Tax Expense', description: 'A percentage of total earnings paid to the government.', type: 'Expense', taxRate: 'BAS Excluded' },
  { code: '610', name: 'Accounts Receivable', description: 'Outstanding invoices the company has issued out to the client but has not yet received in cash at balance date.', type: 'Current Asset', taxRate: 'BAS Excluded' },
  { code: '620', name: 'Prepayments', description: 'An expenditure that has been paid for in advance.', type: 'Current Asset', taxRate: 'BAS Excluded' },
  { code: '630', name: 'Inventory', description: 'Value of tracked items for resale.', type: 'Inventory', taxRate: 'BAS Excluded' },
  { code: '710', name: 'Office Equipment', description: 'Office equipment that is owned and controlled by the business', type: 'Fixed Asset', taxRate: 'GST on Expenses' },
  { code: '711', name: 'Less Accumulated Depreciation on Office Equipment', description: 'The total amount of office equipment cost that has been consumed by the entity (based on the useful life)', type: 'Fixed Asset', taxRate: 'BAS Excluded' },
  { code: '712', name: 'Disability House Equipment', description: 'House equipment that is owner and controlled by the business', type: 'Current Asset', taxRate: 'GST on Expenses' },
  { code: '720', name: 'Computer Equipment', description: 'Computer equipment that is owned and controlled by the business', type: 'Fixed Asset', taxRate: 'GST on Expenses' },
  { code: '721', name: 'Less Accumulated Depreciation on Computer Equipment', description: 'The total amount of computer equipment cost that has been consumed by the business (based on the useful life)', type: 'Fixed Asset', taxRate: 'BAS Excluded' },
  { code: '800', name: 'Accounts Payable', description: 'Outstanding invoices the company has received from suppliers but has not yet paid at balance date', type: 'Current Liability', taxRate: 'BAS Excluded' },
  { code: '801', name: 'Unpaid Expense Claims', description: 'Expense claims typically made by employees/shareholder employees still outstanding.', type: 'Current Liability', taxRate: 'BAS Excluded' },
  { code: '804', name: 'Wages Payable - Payroll', description: 'Where this account is set as the nominated Wages Payable account within Payroll Settings, Xero allocates the net wage amount of each pay run created using Payroll to this account', type: 'Current Liability', taxRate: 'BAS Excluded' },
  { code: '820', name: 'GST', description: "The balance in this account represents GST owing to or from the ATO. At the end of the GST period, it is this account that should be used to code against either the 'refunds from' or 'payments to' the ATO that will appear on the bank statement. Xero has been designed to use only one GST account to track GST on income and expenses, so there is no need to add any new GST accounts to Xero.", type: 'Current Liability', taxRate: 'BAS Excluded' },
  { code: '825', name: 'PAYG Withholdings Payable', description: 'The amount of PAYE tax that is due to be paid', type: 'Current Liability', taxRate: 'BAS Excluded' },
  { code: '826', name: 'Superannuation Payable', description: 'The amount of superannuation that is due to be paid', type: 'Current Liability', taxRate: 'BAS Excluded' },
  { code: '830', name: 'Income Tax Payable', description: 'The amount of income tax that is due to be paid, also resident withholding tax paid on interest received.', type: 'Current Liability', taxRate: 'BAS Excluded' },
  { code: '835', name: 'Net BAS Payable', description: 'Liability', type: 'Liability', taxRate: 'BAS Excluded' },
  { code: '840', name: 'Historical Adjustment', description: 'For accountant adjustments', type: 'Current Liability', taxRate: 'BAS Excluded' },
  { code: '850', name: 'Suspense', description: 'An entry that allows an unknown transaction to be entered, so the accounts can still be worked on in balance and the entry can be dealt with later.', type: 'Current Liability', taxRate: 'BAS Excluded' },
  { code: '860', name: 'Rounding', description: 'An adjustment entry to allow for rounding', type: 'Current Liability', taxRate: 'BAS Excluded' },
  { code: '877', name: 'Tracking Transfers', description: 'Transfers between tracking categories', type: 'Current Liability', taxRate: 'BAS Excluded' },
  { code: '880', name: 'Owner A Drawings', description: 'Withdrawals by the owners', type: 'Equity', taxRate: 'BAS Excluded' },
  { code: '881', name: 'Owner A Funds Introduced', description: 'Funds contributed by the owner', type: 'Current Liability', taxRate: 'BAS Excluded' },
  { code: '900', name: 'Loan', description: 'Money that has been borrowed from a creditor', type: 'Non-current Liability', taxRate: 'BAS Excluded' },
  { code: '960', name: 'Retained Earnings', description: 'Do not Use', type: 'Equity', taxRate: 'BAS Excluded' },
  { code: '970', name: 'Owner A Share Capital', description: 'The value of shares purchased by the shareholders', type: 'Equity', taxRate: 'BAS Excluded' },
];
